// Autogenerated from Pigeon (v4.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTSignInResponse;

@interface FLTSignInResponse : NSObject
+ (instancetype)makeWithResponseUri:(nullable NSString *)responseUri;
@property(nonatomic, copy, nullable) NSString * responseUri;
@end

/// The codec used by FLTUtilsApi.
NSObject<FlutterMessageCodec> *FLTUtilsApiGetCodec(void);

@protocol FLTUtilsApi
- (void)openWebPageTitle:(NSString *)title url:(NSString *)url error:(FlutterError *_Nullable *_Nonnull)error;
///
/// Opens Custom Tab for signing in. Returns response URI with token query parameters.
///
- (void)openSignInCustomTabUrl:(NSString *)url completion:(void(^)(FLTSignInResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FLTUtilsApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTUtilsApi> *_Nullable api);

NS_ASSUME_NONNULL_END
