# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Upload IPA to TestFlight"
    lane :upload do
        app_store_connect_api_key(
            key_id: ENV["ASC_KEY_ID"],
            issuer_id: ENV["ASC_ISSUER_ID"],
            key_filepath: ENV["ASC_KEY_FILEPATH"] || "./secrets/ASC_AuthKey.p8",
        )
        upload_to_testflight(
            skip_waiting_for_build_processing: true,
            ipa: "../build/ios/ipa/Submon.ipa"
        )
    end
end
