name: "Initialize Flutter CLI"
description: "Initializes Flutter CLI commands"

runs:
  using: composite
  steps:
    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-flutter
        path: ./flutter

    - name: Flutter Command Initialize
      shell: bash
      run: |
        if [ ! -d "./flutter" ] ; then
          git clone https://github.com/flutter/flutter.git
        fi
        echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

    - name: Flutter Channel Switch
      shell: bash
      run: flutter channel beta

    - name: Flutter Upgrade
      shell: bash
      run: flutter upgrade