name: Deploy to Internal Track

concurrency:
  group: deploy-internal
  cancel-in-progress: true

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-info:
    name: Get Build Info
    runs-on: ubuntu-latest
    outputs:
      should_build_for_android: ${{
        steps.android-changed-files.outputs.only_changed == 'false' &&
        steps.ios-changed-files.outputs.only_changed == 'false' ||
        steps.android-changed-files.outputs.any_changed == 'true'
        }}
      should_build_for_ios: ${{
        steps.android-changed-files.outputs.only_changed == 'false' &&
        steps.ios-changed-files.outputs.only_changed == 'false' ||
        steps.ios-changed-files.outputs.any_changed == 'true'
        }}
      version_code: ${{ steps.version-code.outputs.version_code }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Android Changed Files
        id: android-changed-files
        uses: tj-actions/changed-files@v32
        with:
          files: |
            android/**

      - name: Get iOS Changed Files
        id: ios-changed-files
        uses: tj-actions/changed-files@v31
        with:
          files: |
            ios/**

      - name: Get Version Code
        id: version-code
        run: echo "version_code=$((${{ github.run_number }}+105))" >> $GITHUB_OUTPUT

  build-android:
    name: Build for Android
    needs:
      - build-info
    if: ${{ needs.build-info.outputs.should_build_for_android == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '*.gradle') }}
          path: ~/.gradle
          restore-keys: ${{ runner.os }}-gradle-

      - name: Init Flutter CLI
        uses: ./.github/actions/init-flutter-cli

      - run: echo $version_code && flutter pub get

      - name: Import Keystore
        run: |
          echo -n '
          ${{ secrets.ANDROID_LOCAL_PROPERTIES }}' >> android/local.properties
          echo -n "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > android/app/release.jks

      - name: Import .env
        run: echo -n "${{ secrets.DOTENV }}" > .env

      - name: Import google-services.json
        run: |
          mkdir -p android/app/src/release
          echo -n ${{ secrets.ANDROID_GOOGLE_SERVICES_JSON_BASE64 }} | base64 -d > android/app/src/release/google-services.json

      - name: Build App Bundle for Android
        run: flutter build appbundle --build-number ${{ needs.build-info.outputs.version_code }}

      - name: Generate Native Debug Symbols
        run: zip -r native_debug_symbols.zip ./build/app/intermediates/merged_native_libs/release/out/lib/* -x "*x86/*"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-aab
          path: |
            build/app/outputs/bundle/release/app-release.aab
            native_debug_symbols.zip
            build/app/outputs/mapping/release/mapping.txt

  build-ios:
    name: Build for iOS
    needs:
      - build-info
    if: ${{ needs.build-info.outputs.should_build_for_ios == 'true' }}
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Cache Pods
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          path: ./ios/Pods
          restore-keys: ${{ runner.os }}-pods-

      - name: Init Flutter CLI
        uses: ./.github/actions/init-flutter-cli

      - run: flutter pub get

      - name: Import Apple Provisioning Profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/Submon_distribution.mobileprovision
          echo -n ${{ secrets.PROVISIONING_PROFILE_WIDGETKIT }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/Submon_WidgetKit_Production.mobileprovision

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATES_P12_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}

      - name: Import .env
        run: echo -n "${{ secrets.DOTENV }}" > .env

      - name: Import GoogleService-Info.plist
        run: echo -n "${{ secrets.APPLE_GOOGLE_SERVICE_INFO_RELEASE_PLIST_BASE64 }}" | base64 -d > ios/GoogleService-Info-release.plist

      - run: |
          flutter precache --ios
          pod install --repo-update
        working-directory: ios

      - name: Build IPA for App Store
        run: flutter build ipa --build-number ${{ needs.build-info.outputs.version_code }} --export-options-plist ios/exportOptions.plist

      - name: Compress IPA
        run: zip submon.zip ./build/ios/ipa/Submon.ipa

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apple-ipa
          path: submon.zip

  deploy-android:
    name: Deploy to Google Play
    needs:
      - build-info
      - build-android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.28.2/yq_darwin_amd64.tar.gz -O - |\
          tar xz
          echo "$(pwd)/yq_darwin_amd64" >> $GITHUB_PATH

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: android-aab

      - name: Import Service Account Key
        run: echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_BASE64 }}' | base64 -d > service_account_key.json

      - name: Deploy to Google Play
        run: |
          versionName=$(cat pubspec.yaml | yq -r '.version | split("+") | .[0]')
          versionNameOption="--version_name $versionName-b${{ needs.build-info.outputs.version_code }}"
          
          bundle exec fastlane supply \
          --aab build/app/outputs/bundle/release/app-release.aab \
          --mapping_paths native_debug_symbols.zip,build/app/outputs/mapping/release/mapping.txt \
          --track internal \
          --skip_upload_images \
          --skip_upload_metadata \
          --skip_upload_changelogs \
          --package_name net.chikach.submon \
          $versionNameOption \
          --json_key service_account_key.json

      - uses: geekyeggo/delete-artifact@v1
        if: always()
        with:
          name: android-aab

  deploy-ios:
    name: Deploy to App Store
    needs:
      - build-ios
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: apple-ipa

      - name: Extract Artifacts
        run: unzip submon.zip

      - name: Import App Store Connect API Key
        run: |
          mkdir ~/private_keys
          echo -n "${{ secrets.APP_STORE_PRIVKEY_P8 }}" > ~/private_keys/AuthKey_${{ secrets.APP_STORE_PRIVKEY_ID }}.p8

      - name: Deploy to App Store
        run: xcrun altool --upload-app --type ios -f "./build/ios/ipa/Submon.ipa" --apiKey ${{ secrets.APP_STORE_PRIVKEY_ID }} --apiIssuer ${{ secrets.APP_STORE_CONNECT_API_ISSUER }}

      - uses: geekyeggo/delete-artifact@v1
        if: always()
        with:
          name: apple-ipa