# This is a basic workflow to help you get started with Actions

name: Deploy to Hosting (web)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ web ]
  pull_request:
    branches: [ web ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Flutter command initialize
        uses: subosito/flutter-action@v2
        with:
          channel: "beta"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter test
        run: flutter test
      - name: Flutter build web
        run: flutter build web

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
