name: Build and Deploy Apps

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-attr:
    runs-on: ubuntu-latest
    env:
      BUILD_NUM_OFFSET: 115
    outputs:
      build_num: ${{ steps.build-attr.outputs.build_num }}
      build_name: ${{ steps.build-attr.outputs.build_name }}

    steps:
      - id: build-attr
        run: |
          echo "build_num=$(($GITHUB_RUN_NUMBER + $BUILD_NUM_OFFSET))" >> $GITHUB_OUTPUT
          echo "build_name=`echo "$GITHUB_REF_NAME" | perl -nle "print $& while m/(?<=v)\d+\.\d+\.\d+/g"`" >> $GITHUB_OUTPUT

  deploy-app-store:
    name: Deploy to App Store
    needs: build-attr
    uses: chika3742/flutter-app-deploy/.github/workflows/ios.yml@main
    with:
      build-name: ${{ needs.build-attr.outputs.build_name }}
      build-number: ${{ needs.build-attr.outputs.build_num }}
    secrets:
      provisioning_profile_1_base64: ${{ secrets.PROVISIONING_PROFILE }}
      provisioning_profile_2_base64: ${{ secrets.PROVISIONING_PROFILE_WIDGETKIT }}
      codesign_cert_base64: ${{ secrets.APPLE_CERTIFICATES_P12_BASE64 }}
      codesign_cert_pw: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}
      google_service_info_plist_base64: ${{ secrets.APPLE_GOOGLE_SERVICE_INFO_RELEASE_PLIST_BASE64 }}
      asc_key_id: ${{ secrets.APP_STORE_PRIVKEY_ID }}
      asc_issuer_id: ${{ secrets.APP_STORE_CONNECT_API_ISSUER }}
      asc_key_base64: ${{ secrets.APP_STORE_PRIVKEY_P8_BASE64 }}
      dotenv_base64: ${{ secrets.DOTENV_BASE64 }}

  deploy-play-store:
    name: Deploy to Play Store
    needs: build-attr
    uses: chika3742/flutter-app-deploy/.github/workflows/android.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      build-name: ${{ needs.build-attr.outputs.build_name }}
      build-number: ${{ needs.build-attr.outputs.build_num }}
      wif-audience: ${{ vars.WI_AUDIENCE }}
    secrets:
      keystore_base64: ${{ secrets.ANDROID_KEYSTORE }}
      key_properties_base64: ${{ secrets.ANDROID_KEY_PROPERTIES_BASE64 }}
      google_services_json_base64: ${{ secrets.ANDROID_GOOGLE_SERVICES_JSON_BASE64 }}
      wif_provider: ${{ secrets.WI_PROVIDER }}
      wif_service_account: ${{ secrets.WI_SERVICE_ACCOUNT }}
      dotenv_base64: ${{ secrets.DOTENV_BASE64 }}

concurrency:
  group: deploy
  cancel-in-progress: true
